[kubernetes]
disabled = false

[direnv]
disabled = false

[git_metrics]
disabled = false

[character]
success_symbol = "ğŸ‘‰"
vicmd_symbol = "âœŒï¸"
error_symbol = "ğŸš¨"

[directory]
style = "blue bold"
